version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
      - 4000:4000
    volumes:
      - .:/app
      - gem_cache:/gems
    env_file:
      - .env
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server
      - RAILS_ENV=development

  webpack_dev_server:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  database:
    image: docker.io/postgres:15-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  gem_cache:
